// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://touaxqfnzttmuznspnee.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRvdWF4cWZuenR0bXV6bnNwbmVlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1NTcwMTIsImV4cCI6MjA2ODEzMzAxMn0.0XB5bY56c_ODvb1JyGnMRauFXqeKzncO749TN6WlN-0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});